version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: "${DKFILE}"
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    environment:
      - ADDRESS=${ADDRESS}

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: homehub
      MYSQL_USER: admin
      MYSQL_PASSWORD: asos
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
